### ISSUE TITLE
What are fallback locales used for?

### ISSUE THREAD

**Issue by ElForastero** [lus/fluent.go#1]
Hey,

As I understand from the API, there's no way to actually translate the massage to the particular language, right?

I mean, I can set `fallback` locales, but they are not even used in `FormatMessage` func.

I'm just a bit confused how it was designed and how to translate to any other language?

**Comment by lus** [comment]
Hello!

[Project Fluent](https://projectfluent.org/) is just a localization system, nothing is translated like you may know it from translators like Deepl or Google Translate.

Localization is often done by creating multiple source files (JSON, YML, etc.) that contain the translations for the particular language.
An app thus could have the following two files:

`en.json`
```json
{
    "greeting": "Hello, {user}!"
}
```

`de.json`
```json
{
    "greeting": "Hallo, {user}!"
}
```

Whenever the app renders the greeting to a particular user, the message is loaded from the file that contains the translations for the language this user chose before.

Fluent represents an alternative syntax for those files to make it easier to write naturally sounding translations.

That said, the language(s) you pass to the `fluent.NewBundle` function will be used to format numbers and dates into the target language in the future, but that feature is not yet implemented into this library.

I hope I could help making things a bit more clear ^^

**Comment by ElForastero** [comment]
@lus  Yes, that's totally understandable that this is not a translation but internationalization library.

The problem that I faced is that it's not possible to use a single bundle of all the messages I have (all the languages).

It appears that I must create a new bundle for every single language my system has.

```go
// There's no way to pass a concrete language tag, like `language.DE`
// and I should use a different bundle if I want to use German, for example
message, _, _ := englishBundle.FormatMessage("greeting", fluent.WithVariable("subject", "world"))

// And if German string is needed, then
message, _, _ := germanBundle.FormatMessage("greeting", fluent.WithVariable("subject", "welt"))
```

As an example, this is how it is implemented in the https://github.com/nicksnyder/go-i18n:

```go
func(w http.ResponseWriter, r *http.Request) {
    accept := r.Header.Get("Accept-Language")
    localizer := i18n.NewLocalizer(bundle, accept)
}
```

Actually, it stores all the language and all the messages in a single `bundle` that later may be used to localize based on the `Accept-Language` for instance.

----

I was also thinking that it would be nice not to reinvent the wheel and instead of writing some i18n specific logic here, it would be nice to just export the functionality of the `parser`, to be able to unmarshal random strings.

go-i18n library has an ability to register a custom unmarshal func, and if I could use this package just for unmarshaling fluent messages, it would be just great

Consider this usecase:

```go
package main

import (
	"net/http"

	"github.com/lus/fluent.go/fluent"
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

func handler(w http.ResponseWriter, r *http.Request) {
	bundle := i18n.NewBundle(language.English)
	bundle.RegisterUnmarshalFunc("ftl", fluent.Unmarshal) // ← This is the most important part
	bundle.MustLoadMessageFile("common.en.ftl")
	bundle.MustLoadMessageFile("common.de.ftl")
	bundle.MustLoadMessageFile("common.es.ftl")

	accept := r.Header.Get("Accept-Language")
	localizer := i18n.NewLocalizer(bundle, accept)

	message := localizer.MustLocalize(&i18n.Message{ID: "helloworld"})
}

```

**Comment by lus** [comment]
The problem I see there is that, while applying similar concepts, nicksnyder/go-i18n works fundamentally different.
Pluralized strings are written like

```toml
[PersonCats]
description = "The number of cats a person has"
one = "{{.Name}} has {{.Count}} cat."
other = "{{.Name}} has {{.Count}} cats."
```

(`one` and `other` are treated as completely different strings)

while Fluent uses

```ftl
person-cats =
    { $name } has { $count ->
        [one] one cat.
        *[other] { $count } cats.
    }
```

which is a completely unique syntax.

Thus, a simple key-value mapping like go-i18n uses is not that easy to implement and would lead us to the same situation Project Fluent wants to move away from, namely having key-value translation files without any logic.

That said, you'll have to look up the Fluent bundle to use yourself before translating something. A very basic solution to that would be a `map[language.Tag]*fluent.Bundle` map, but that is up to you.

If you, for some reason, want to access the parser directly, you can simply use the included `parser` package which builds an AST.

**Comment by ElForastero** [comment]
Hm... Yeah, now I see it. Approaches are kinda different 🤔

Thank you for pointing this out.

**Comment by lus** [comment]
No problem!
Do you have any other questions or can this issue be marked as resolved?

**Comment by ElForastero** [comment]
Nope, let's close it then 🙂
